### ISSUE TITLE
[Bug]A minecraft verison 1.19 -> 1.19.2 server

### ISSUE THREAD

**Issue by addpromax** [WiIIiam278/HuskSync#106]
[HuskSync] Cannot set data for Alicia_Keys because the Minecraft version of their user data (1.19.2) is newer than the server's Minecraft version (1.19-R0.1-SNAPSHOT)
How to deal this

**Comment by WiIIiam278** [comment]
Open ticket on discord & verify purchase for support as this is user error and not a bug
