### ISSUE TITLE
Command improvements

### ISSUE THREAD

**Issue by kalleswe** [WiIIiam278/HuskSync#115]
Hello! I love huskchat, it's so simple and well coded.
But I'm missing a feature that I love from other chats. The possibility to toggle staff chat with the same command.
/sc to toggle on, then /sc to toggle back off. Instead of having to type /g or /global.
Would it be possible to add such a feature. Maybe make it a on/off setting in the conf for that?

**Comment by WiIIiam278** [comment]
This is the wrong repository -- but the way HuskChat is designed this wouldn't really work unfortunately, so I'm just going to close this
