### ISSUE TITLE
Adapt to Fabric and ask for contribution code-related notes.

### ISSUE THREAD

**Issue by hanbings** [WiIIiam278/HuskSync#117]
Hello!
I stumbled across this plugin and it works brilliantly! Whether it is user experience or code architecture design, thank you for your efforts!
After trying to read the code, I found that the project has decoupled the relevant parts of the server. I wonder if you have an adaptation plan for Fabric?
I'd like to try to do a port to Fabric, targeting servers who only use Fabric's server-side mods.
If you are willing to maintain the code of Fabric, I will report the progress and adaptation and initiate a PR in the next one to two weeks.

_English is not my first language, so my wording and grammar may not be very appropriate. Please forgive me and point out my mistakes._ 😊

**Comment by WiIIiam278** [comment]
In short, yes -- I designed HuskSync's core logic decoupled to allow for that in the future -- if you want to port to fabric and maintain it, please go right ahead and PR, that's exactly the sort of reason I make the source available for my stuff :)

Same with all my plugins, really, I'd very much be keen to add Fabric support. I actually tried doing a sponge version of Homes, just didn't get round to it yet.

**Comment by WiIIiam278** [comment]
Closed by #217

**Comment by WiIIiam278** [comment]
Fabric support has now been merged 🎉
