### ISSUE TITLE
(Locked) Map synchronization

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#14]
The ability for map items to synchronize cross-server. Would require some NMS and probably only be able to work with "locked" maps (i.e uneditable ones). Would need to serialize the map canvas as an image essentially when the map is "locked" and probably put it inside a PersistentDataContainer tag and add that to the map item which would then be loaded from when the player pulls it out.

**Comment by Iotados** [comment]
How will this manage the ability to pull the correct image from two servers? as using map IDs is not possible unless you can enforce a single ID system across the two systems

**Comment by WiIIiam278** [comment]
> How will this manage the ability to pull the correct image from two servers? as using map IDs is not possible unless you can enforce a single ID system across the two systems

The plan is to serialize map data (which is 128x128x16 colors in size; so not too large) when the map is locked, then put that data inside a PersistentDataHolder (NBT tag) within the item. When the player opens the map on another server, if it has that holder HuskSync will apply the map image from the holder.

**Comment by Uharn** [comment]
I have players that made a full card system using maps... to play poker and blackjack. Currently they are restricted to one server but that would be very nice to be able to use those maps on other servers!
![image](https://user-images.githubusercontent.com/61411441/167226187-98007d52-fd66-446a-9d4a-1fd4e5148eea.png)
