### ISSUE TITLE
After death, choose to return to the title bar and lose the item

### ISSUE THREAD

**Issue by sekaom** [WiIIiam278/HuskSync#142]
I'm using HuskSync2.2.5 (2.2.4 has the same problem). When the player dies without using instructions, he chooses to return to the title bar instead of being reborn. When they enter the server again, their backpack items will be lost. I only configured mysql and redis in the config file. This problem will be triggered by both java (1.19.2) and the bedrock version (1.20.0) of the geyser agent.

**Comment by WiIIiam278** [comment]
> backpack items 

Do you just mean the ordinary player inventory?

I think this is more of a support issue since this isn’t reproducible by default. Please open a ticket in the discord :)

**Comment by sekaom** [comment]
I think this is a bug. 
  
After others gave me feedback on this problem, I tested it many times, and the problem is still simple and reproducible.  
    
I just want to talk about this issue, not to get support.  
  
[here](https://gist.github.com/sekaom/bd9b4f11144f0bc6fca61338e83b4b02) is my config.yml file

**Comment by sekaom** [comment]
> > backpack items
> 
> Do you just mean the ordinary player inventory?
> 
> I think this is more of a support issue since this isn’t reproducible by default. Please open a ticket in the discord :)

I think this is a bug. 
  
After others gave me feedback on this problem, I tested it many times, and the problem is still simple and reproducible.  
    
I just want to talk about this issue, not to get support.  
  
[here](https://gist.github.com/sekaom/bd9b4f11144f0bc6fca61338e83b4b02) is my config.yml file

**Comment by WiIIiam278** [comment]
Please open a ticket on the Discord server and request help :) -- we can't provide support services on here. I'm not readily able to reproduce this; seems likely it concerns your setup.
