### ISSUE TITLE
Server  crashes on world save

### ISSUE THREAD

**Issue by nicolube** [WiIIiam278/HuskSync#152]
We had some server-crashes, it stopped since we disabled save_on_world_save.

Could u pls look into that?

Crash reports and additional information:
https://github.com/PurpurMC/Purpur/issues/1391
https://github.com/PaperMC/Paper/issues/9528

**Comment by WiIIiam278** [comment]
I _think_ it's caused by the way Purpur offloads certain functionality on world save to different threads.

**Comment by nicolube** [comment]
@WiIIiam278 We have verified the issue on both paper and Purpur

**Comment by nicolube** [comment]
Fixed in #153
