### ISSUE TITLE
PDC sync feature doesn't support arbitrary types

### ISSUE THREAD

**Issue by Akiranya** [WiIIiam278/HuskSync#155]
Hi William! owo

I have a plugin (https://github.com/Ehhthan/MMOBuffs) that stores PDC on the player so I wanted HuskSync to sync the PDC data between servers. But the problem is that HuskSync can't sync the PDC data of MMOBuffs. I guess this is because MMOBuffs uses their own java types for the PDC while HuskSync only supports limited "primitive" types.

Side notes: the author (Ehhthan) suggests we can use his own PDC sync plugin to sync the PDC data, which seems to work with MMOBuffs (as he has claimed it xD). This is the PDC sync plugin: https://github.com/Ehhthan/PersistentDataSync

And I see it use the NBT API (by tr7zw) to serialize/deserialize the PDC data across servers, tho I'm not sure how you think the usage of the API in HuskSync codebase if it can fix the errors.

This issue has already been reported to [discord](https://discord.com/channels/818135932103557162/1114917962239967272) by me but since it's a bug I reported it to github as well so it can be easier to track.

**Comment by WiIIiam278** [comment]
hey! :)

Yeah I’ve gotten a bevelege of complaints about this over while: the bottom line is this requires using nbtapi to do stuff the old fashioned way. MMOItems and Slimefun (some of which use raw nbt access on items themselves similarly have issues as they rely on nbt access)

Which is fine; my main issue with such is trying to avoid maintenance and stability issues as I prefer to use the spigot APIs where available.

I’m working on some refactor work in another branch. I think when that’s done I’ll look at supporting custom nbt / PDC types a bit better

thanks!!

**Comment by WiIIiam278** [comment]
closed in v3.0
