### ISSUE TITLE
If die and leave the server, inventory items will disappear.

### ISSUE THREAD

**Issue by xOTA9985** [WiIIiam278/HuskSync#156]
I want to explain that when I try to leave the server without respawning and come back again, my inventory items will sync once, but they disappear after the sync. 
Later, when I checked the saved "disconnect" data, the inventory items were empty.

YT link: https://youtu.be/hhQh_Isbero

*I'm pretty sure everything in config.yml is correct and sync works fine.

**Comment by WiIIiam278** [comment]
Hi there, please get in touch on our Discord for support &mdash;
