### ISSUE TITLE
Locked maps not in player inventories on servers other than their origin wont persist their contents after restart

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#157]
https://youtu.be/5S7SXrijK4w

Probably need to listen to the map open event or something like that

**Comment by jdkeke142** [comment]
It seems that maps don't persist either when a map is out of the player's inventory (containers) and the chunk is unloaded, the map becomes empty and the player have to return to the server on which the map was created to restore its contents.
