### ISSUE TITLE
Item loss on server stop

### ISSUE THREAD

**Issue by nicolube** [WiIIiam278/HuskSync#159]
HuskSync does not store inventorys on server stop

We have about 150 Players, and we get fequent complains the there are duplicated or lost items when we do restarts

**Comment by WiIIiam278** [comment]
Hi there :)

HuskSync should handle this &mdash; see [here](https://github.com/WiIIiam278/HuskSync/blob/9db9a3e72141b6bc36a21bfbf3138663ab199f1d/common/src/main/java/net/william278/husksync/listener/EventListener.java#L243-L259) for the underlying logic.

The issue I believe that causes this not to work correctly is that the [invocation of `setUserData`](https://github.com/WiIIiam278/HuskSync/blob/9db9a3e72141b6bc36a21bfbf3138663ab199f1d/common/src/main/java/net/william278/husksync/database/MySqlDatabase.java#L354-L356) attempts to fire the DataSaveEvent; something that can't happen as the server is shutting down.

On the dev-branch I'm [refactoring](https://github.com/WiIIiam278/HuskSync/tree/v3-work) this so as to either not fire the event or handle things slightly differently on shutdown to prevent this issue.

If you require further support or advice, please purchase a copy of the plugin and join the Discord for support.

Warm regards
Will

**Comment by nicolube** [comment]
Well, I have and I'm
also known as @DevMagic

**Comment by WiIIiam278** [comment]
I do believe this is resolved by the open PR — but that isn’t production ready just yet. Thanks

**Comment by WiIIiam278** [comment]
closed in v3.0
