### ISSUE TITLE
Bug duplication when a server doesn't have to sync inventories

### ISSUE THREAD

**Issue by FaMa91** [WiIIiam278/HuskSync#161]
How to reproduce the bug:
configure 2 servers (A and B) to sync inventories and a third server (C) with inventory sync disabled.

1: In server A drop something then move to server C (the inventory is different as expected);
2: Move from server C to server B (the inventory here is the same from server A but what you dropped is still in the inventory)
3: Move from server B to server C (the item you dropped are still there, but you have the same items in the inventory)

config for server A and B: https://pastebin.com/49ZhSF9H
config for server C: https://pastebin.com/ZH9yu6ar

Using latest version: 2.2.8

**Comment by WiIIiam278** [comment]
hi there :)
due to the nature of this issue, further troubleshooting is needed. Please make a ticket on Discord and verify your purchase so we can help you resolve this.
