### ISSUE TITLE
Support RedisBungee?

### ISSUE THREAD

**Issue by MeowRay** [WiIIiam278/HuskSync#20]
I'm deciding whether to buy this plugin.
The README mentioned that multiple proxies are not supported. Is there any plan to support it in a month?

**Comment by WiIIiam278** [comment]
There's no immediate plans to support multiple proxies. Velocity is supported, which can handle players at huge scales - multiple proxies are only really needed if you're looking at 1000+ players

**Comment by MeowRay** [comment]
> There's no immediate plans to support multiple proxies. Velocity is supported, which can handle players at huge scales - multiple proxies are only really worth considering if you're looking at 1000+ players simultaneously

Or provide a storage mode that doesn't require a proxy to improve adaptability?

**Comment by WiIIiam278** [comment]
> > There's no immediate plans to support multiple proxies. Velocity is supported, which can handle players at huge scales - multiple proxies are only really worth considering if you're looking at 1000+ players simultaneously
> 
> Or provide a storage mode that doesn't require a proxy to improve adaptability?

That’s probably how this would be implemented, via storing on the redis DB itself
