### ISSUE TITLE
Save player data on the WorldSaveEvent

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#21]
In addition to how it is currently where data is only saved on logout.

**Comment by houtblok** [comment]
My suggestion for this would be saving online player's data on WorldSaveEvent, this way the world data (Chests) and player data (Inventories) are never out of sync when a server suddenly crashes.

**Comment by Uharn** [comment]
I just wanted to up that implementation... it's dangerous for me to migrate because of that

**Comment by WiIIiam278** [comment]
> I just wanted to up that implementation... it's dangerous for me to migrate because of that

Well, this is something that'd only affect if your servers were prone to crashing - it's not a hugely scary thing to not have this. It's a nice little bit of assurance, though.

**Comment by Uharn** [comment]
Crashes do not happens a lot (i would say 1-2 times a month on my side) and it's generaly not a so big issue, but when they do, if players lose custom items that takes month of farming to get... then it gets problematic.
