### ISSUE TITLE
Death one second before cross-server transfer will cause the inventory to be lost.

### ISSUE THREAD

**Issue by DCE-114514** [WiIIiam278/HuskSync#238]
Because turning on the death save will cause some players' backpacks to disappear after death (even if itemtokeep is turned on), I turned off the death save. However, I don't think this problem is related to the death save. I was using huskhomes for the last step of cross-server transfer. The death interface was transmitted after being blown up by a creeper in seconds (the server enabled inventory saving). After that, the inventory disappeared. After dumping a file, I checked and found that the inventory became empty. The latest version of the plug-in server used. The version is 1.20.4
The Google Translate I used for this article may not be fluent :)  By the way, after I upgraded to 1.20.4, some of the chat bar buttons in huskhomes cannot be clicked (such as returning to the previous location).
![屏幕截图 2024-02-05 055206](https://github.com/WiIIiam278/HuskSync/assets/132117183/0d4e8d92-bb71-40e5-b41a-b0106e77e61f)

**Comment by WiIIiam278** [comment]
Hey there - could you please join the Discord and get help through our support ticket process so I can look into this for you?

Thank you :)
