### ISSUE TITLE
Problems with clusters

### ISSUE THREAD

**Issue by kforbro** [WiIIiam278/HuskSync#256]
There are two servers: A (cluster lite) and B (cluster grief), on both servers, different cluster_ids, different mysql credentials and server.yml (same as in velocity config) are specified in the configs.

After upgrading from 3.2 to 3.4 (I deleted the configs and re-specified all the fields), a problem appeared that magically players very rarely manage to transfer inventory and statistics from server A to server B, provided different cluster_ids and database credentials. This happens rarely, by accident, and there is no exact way to reproduce it.
Some players said the following: you need to play for several hours on server A and log in to server B (provided that you have never logged in to server B before), then inventory and everything else from server A appear on server B. But maybe that's not the case.

LOCKSTEP, Paper 1.20.1

**Comment by WiIIiam278** [comment]
Please open a support ticket for assistance so we can investigate in more depth
