### ISSUE TITLE
Wiki problem

### ISSUE THREAD

**Issue by SnowCutieOwO** [WiIIiam278/HuskSync#267]
Hey author, me again!
I'm translating your wiki and I found that there's some hidden pages that are not shown in sidebar index.
For example, the chapter of `Unsupported Versions`.
I would ask is this a mistake or just on purpose?
Please reply soon as I'm checking wiki's content are correct in my translation

**Comment by WiIIiam278** [comment]
hey,
wikis aren't currently translatable however if there's interest ill add this as a website feature to let folks supply international locales :)

**Comment by SnowCutieOwO** [comment]
> hey,
> wikis aren't currently translatable however if there's interest ill add this as a website feature to let folks supply international locales :)

I've already translated the whole wiki, and you could see it here:
https://snowcutieowo.github.io/HuskSync

**Comment by WiIIiam278** [comment]
That's very helpful, thanks :) -- I think it'd be nice if I could add internationalisation support to my website to make it easier for users who don't speak English to find my stuff. If you'd like, I'd accept a pull request with the files to /docs/<language_code>/... and from there ill look at how to update my website to support letting users switch their language

**Comment by WiIIiam278** [comment]
Hello, I have posted details about this here if you wish to contribute docs translations: https://william278.net/translate

**Comment by SnowCutieOwO** [comment]
> Hello, I have posted details about this here if you wish to contribute docs translations: https://william278.net/translate

Quite difficult since I'm using Docsify on my personal wiki translation, I suggest keep the originals and just left a link, for both maintainability and clean.

**Comment by WiIIiam278** [comment]
> > Hello, I have posted details about this here if you wish to contribute docs translations: https://william278.net/translate
> 
> Quite difficult since I'm using Docsify on my personal wiki translation, I suggest keep the originals and just left a link, for both maintainability and clean.

That's fine, it's up to you of course - I just figured it's a bit easier for user discoverability for docs to all be in the same place :).

If you decide you'd like to take the time to separate it out, just submit a PR. Thanks for your work!
