### ISSUE TITLE
Can't Sync Data

### ISSUE THREAD

**Issue by DJelly4K** [WiIIiam278/HuskSync#27]
MySQL, Redis connection is normal, no error is reported in the background of the agent, but the player has not successfully synchronized data when transferred to another server, the prompt shows that it has been synchronized, but there is no change, and the downstream server has an error in the background
At the same time, ALL CHEST MENUS cannot be opened

Proxy: Velocity 3.1.1
Downstream Servers: [Mirai](https://github.com/etil2jz/Mirai) (A [Pufferfish](https://github.com/pufferfish-gg/Pufferfish) fork)
MariaDB: 10.5.6
Redis: 5.0.14.1 [(Windows fork)](https://github.com/tporadowski/redis/)
HuskSync: 1.3.3+rev.46f791d-indev (latest github commits and build by myself)

![image](https://user-images.githubusercontent.com/68630033/161664361-02cbca8f-ccb6-4f5b-9476-34e61fb18f4d.png)

**Comment by DJelly4K** [comment]
why close this

**Comment by WiIIiam278** [comment]
This is an issue with a development build or a setup issue requiring support, not a verifiable/replicable bug :)
HuskSync is a premium resource and we offer support for customers on our discord. Please check the LICENSE for more information.
