### ISSUE TITLE
Bug: Command Template in /userdata show <user> when usernames has _ _

### ISSUE THREAD

**Issue by nicolube** [WiIIiam278/HuskSync#270]
For some reason the command tempate in `/userdata show` for `fake__simon` is `/inventory fake_\_Simon 2bf53837-f2a8-4222-89dd-4397994ae755`

**Comment by ProdPreva1l** [comment]
This is a known issue, it is todo with the text formatter we use escaping underscores. No ETA for a fix as of now

**Comment by WiIIiam278** [comment]
Already fixed in fact, just need to push a commit replacing MineDown-adventure with my own William278 flavored MineDown fork.
