### ISSUE TITLE
Multi Player Data

### ISSUE THREAD

**Issue by zimzaza4** [WiIIiam278/HuskSync#28]
Multiple subservers use different player data.

**Comment by WiIIiam278** [comment]
This isn't an issue, this is a support question. Please get in touch on our Discord and provide proof of purchase for support :-)

**Comment by DJelly4K** [comment]
You can create

**Comment by DJelly4K** [comment]
you can create different cluster table
![image](https://user-images.githubusercontent.com/68630033/167256867-65b7b878-b1f7-4ac7-acef-641291feb898.png)
