### ISSUE TITLE
Skin and world chunks won't load properly if `cancel_packets: true` 

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/HuskSync#286]
On player join, I perceive 2 minor issues with packet that:
- Make player skin only load the base image, layer 2 of the skin is missing
- Chunks (on paper) are loaded a few around the player

If I click on the setting -> video menu, it forces the game to reload and help the skin and chunks to reload properly.

My suggestion is adding one more allow packet to not cancel those actions.  I added `Client.SETTINGS` to `ALLOWED_PACKETS` list to test it and it works as expected.

Edit: The problem happens if I use `cancel_packets: true` in the config.yml file.

**Comment by WiIIiam278** [comment]
Feel free to open a PR :)
