### ISSUE TITLE
Sync player's PersistentDataContainer

### ISSUE THREAD

**Issue by mfnalex** [WiIIiam278/HuskSync#30]
Hi, are there plans to make it possible to also sync the player's PersistentDataContainer?

The reason is that I thought that HuskSync aims to make "switching between servers" behave the same as "switching between worlds" in vanilla. In vanilla, that includes all NBT tags, including the "BukkitValues" tag (which contains the PDC data).

(Reason why this would be nice is because many plugins, including mine, store player data in the PDC)

**Comment by WiIIiam278** [comment]
Hi there,
I was aware of PersistentDataContainer, but I didn't know players also had one. PersistentDataContainers within ItemMeta is already serialized.
Doing this will be added to the to-do list.

**Comment by WiIIiam278** [comment]
Closed via #33
