### ISSUE TITLE
Saving data on WorldSaveEvent can cause synchronous tick delays (lag spikes in very extreme cases)

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#31]
Unexpectedly high tick durations due to saving everyone's data on the WorldSave event. An additional flag to data saving should be added such that it can be specified to be done asynchronously as should be the case.
![image](https://user-images.githubusercontent.com/31187453/175652312-4bf66165-ddbf-4dbc-8526-01a9539f547f.png)

Workaround: increase the intervals of your world save, or disable saving on world-save in HuskSync's config.

**Comment by ZConnorZ** [comment]
It looks like the world-save configuration option is not working, it is disabled, but the plugin continues to use it.

**Comment by WiIIiam278** [comment]
> It looks like the world-save configuration option is not working, it is disabled, but the plugin continues to use it.

You need to disable it on the HuskSync config on each of your bukkit servers (HuskSync/config.yml)
Is it disabled on every bukkit server? Make sure to restart after applying and saving this change.

**Comment by ZConnorZ** [comment]
On each server? Okay, I'll check everything again today!

**Comment by ZConnorZ** [comment]
It didn't help, the option is disabled in the config. But the plugin uses.

**Comment by WiIIiam278** [comment]
Hmm...are you sure? Could you send a timings report with this disabled (double check it's off on the Bukkit config)

**Comment by ZConnorZ** [comment]
I'm sure. I have disabled everywhere. Everything is the same in timings.

**Comment by ZConnorZ** [comment]
Hi bro. How are things with the plugin. My server will burn down soon. 💢

**Comment by WiIIiam278** [comment]
Hi there, this issue will be addressed in the next update, hopefully soonish.

**Comment by ZConnorZ** [comment]
My server burned down

**Comment by WiIIiam278** [comment]
I'm sorry to hear that. My condolences to the server's family.

**Comment by ZConnorZ** [comment]
When will the fire extinguisher be ready?

**Comment by WiIIiam278** [comment]
I can't provide time frames. Soon. Please be a little patient-spamming my emails won't make it faster.

**Comment by WiIIiam278** [comment]
Closed via #33
