### ISSUE TITLE
[1.20.6 Paper #130] the plugin doesn't load

### ISSUE THREAD

**Issue by LucidAPs** [WiIIiam278/HuskSync#310]
When I was on 1.20.4 everything was working fine, but updating to 1.20.6 and the plugin no longer works
https://mclo.gs/Nsc9dYs
also I cannot join the discord, ether the invite links are bad or I have been banned years ago.

**Comment by WiIIiam278** [comment]
I am unable to reproduce, and so this is a support matter that would need to be addressed on Discord. In the exceptional circumstance in which you've been banned, we can no longer provide any help to you for using the plugin.
Thank you for your understanding.
