### ISSUE TITLE
Add a warning when server.yml is unset while using LOCKSTEP

### ISSUE THREAD

**Issue by romanalexander** [WiIIiam278/HuskSync#314]
https://github.com/WiIIiam278/HuskSync/blob/master/common/src/main/java/net/william278/husksync/config/Server.java#L56-L59

I think having a warning or fatal here would be safer for people that didn't follow the set-up correctly or have some other problem with their containers' filesystem. Thoughts?

**Comment by WiIIiam278** [comment]
yeah, sure, seems perfectly reasonable to me.
