### ISSUE TITLE
Filled map are not transferred when using a schulker box

### ISSUE THREAD

**Issue by BAD7777** [WiIIiam278/HuskSync#322]
When you make a map immutable in the cartography table and put them in a shulker box, they do not transfer when reconnecting to another server and remain empty.

![image](https://github.com/WiIIiam278/HuskSync/assets/129652614/185817e0-e061-427c-9df9-d954d60b920b)

**Comment by WiIIiam278** [comment]
hm, lol. I never considered this. A fix for shulker boxes should be possible at least, though this might never fully work with stuff like modded fabric itemholder items/pouches. will have to investigate.

**Comment by WiIIiam278** [comment]
Data will now be persisted to 'em. You may need to swap servers or place in an item frame and reload the chunk to get them showing up
