### ISSUE TITLE
Can't sync between 1.21 and 1.20 or bellow.

### ISSUE THREAD

**Issue by Fadouse** [WiIIiam278/HuskSync#343]
I had just updated my server Minecraft version to 1.21, and the effect data had a sync error.
In 1.21 Server, the player got a speed effect and couldn't clear.
Also, the data can't sync between 1.21 and 1.20; the client will receive the error "Can't sync your data, please contact your admin" when trying to join back to the 1.20 server.

**Comment by WiIIiam278** [comment]
You can't sync data between mismatching versions. Among other things, there's different items and NBT formats between versions; HuskSync will safely fail the sync to prevent data corruption.

For further support, get in touch on Discord
