### ISSUE TITLE
Attributes not synced properly on 1.21, can cause exceptions

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#348]
Attributes were changed significantly in 1.21, and simultaneously supporting the new and old system is a technical challenge.

**Workaround**: _Turn attribute syncing off_, (or add particularly problematic attributes to the ignore list in config).

* "Attribute Modifier Already Applied" exception: https://hastebin.skyra.pw/ironodocap.pgsql
* "Error reflectively creating keyed attribute modifier" exception: https://mclo.gs/95I5Yrv

**Comment by JuraRusan** [comment]
Hello @WiIIiam278,

Sorry for the inconvenience. Could you please clarify which specific attributes are causing the issues? We are using version `HuskSync-Paper-3.7-50eb9a7+mc.1.21.1.jar` and are encountering this error.
Or perhaps it would be better to completely disable the attribute feature, as you mentioned earlier?

_This is the plugin version you provided us in the Discord ticket to fix the issue https://github.com/WiIIiam278/HuskSync/issues/371._

Thank you!

**Comment by WiIIiam278** [comment]
> Hello @WiIIiam278,
> 
> 
> 
> Sorry for the inconvenience. Could you please clarify which specific attributes are causing the issues? We are using version `HuskSync-Paper-3.7-50eb9a7+mc.1.21.1.jar` and are encountering this error.
> 
> Or perhaps it would be better to completely disable the attribute feature, as you mentioned earlier?
> 
> 
> 
> _This is the plugin version you provided us in the Discord ticket to fix the issue https://github.com/WiIIiam278/HuskSync/issues/371._
> 
> 
> 
> Thank you!

Hi there, you'll need to use a new build with a few changes I made yesterday. Please go to https://william278.net/project/husksync and select "Alpha" release channel and "Paper", "Paper 1.21.1" as your platform and download the latest alpha build :)

**Comment by JuraRusan** [comment]
Thank you very much!
