### ISSUE TITLE
If potion effect syncing is off while attribute syncing is on, discrepancies occur

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [WiIIiam278/HuskSync#349]
I believe I've found bug for obtaining permanent minecraft effects if they modify attributes.

If I've attributes and potion_effects sync enabled and give myself effect that modify attributes then after switching servers attributes are beeing synced, but effects arent, so they are never beeing removed from player.

Example:
Give yourself a Haste/Strength/Mining Fatigue etc.  effect, then switch server. Attributes would never be taken off from the player, because potion effect is not beeing synced therefore there is nothing that would remove attribute.
![image](https://github.com/user-attachments/assets/ba9d1264-0182-4b31-9e77-1b9edec99c5a)

Info:
![image](https://github.com/user-attachments/assets/08a49ab9-039f-443d-ae9f-46216a7ce801)
![image](https://github.com/user-attachments/assets/ca152672-5ec6-4d9d-b3f2-0895594dfd4a)
![image](https://github.com/user-attachments/assets/4bd23977-0491-46d7-9e67-2b0868ccd42a)
I've disabled attributes syncing after spoting this issue

**Comment by WiIIiam278** [comment]
Interesting. Currently Attribute syncing must be on to use potion effect syncing but not the other way. Should prob have a look at this.
