### ISSUE TITLE
Attributes from the armor remain, but the armor itself is not present.

### ISSUE THREAD

**Issue by BAD7777** [WiIIiam278/HuskSync#352]
**Attributes from the armor remain, but the armor itself is not present.**
HuskSync version 3.6.7-c949c97
A modern, cross-server player data synchronization system
Website: https://william278.net/
Author: William278

Checking version, please wait...
Current Purpur Version: 1.21-2272-b2d1fea (MC: 1.21)
You are running the latest version
Previous: 1.20.6-2233-0d6766e (MC: 1.20.6)

![image](https://github.com/user-attachments/assets/4dd4ae82-0bd0-4c14-acac-6e986b34ada1)

**Comment by WiIIiam278** [comment]
Closing in favor of #348
