### ISSUE TITLE
[feature request] sync direction whitelist

### ISSUE THREAD

**Issue by quiquelhappy** [WiIIiam278/HuskSync#356]
welp, a bit of an unusual request, but I would like husksync to only sync the inventories when switching between two specific servers:
- server1 <-> shops
- server2 <-> shops

but not between server1 <-> server2

yes, im aware that a player could switch to shops and traverse the tree that way and perform a sync, but in our case we use preauthorized sessions so its not a problem for us

i know about the cluster thing, but its a single identifier thus forcing server1 and server2 inventory sync, the only thing missing parameter would be a sync direction whitelist, so the shops server would have
```yml
allow_from:
- server1
- server2
```

and the other two servers would have just
```yml
allow_from:
- shops
```

**Comment by WiIIiam278** [comment]
Thanks for your request. This isn't planned within the scope of HuskSync at this time. Feel free to fork and adjust the plugin for your own needs, however :)
