### ISSUE TITLE
Shulker boxes stack sizes reset to 1 upgrading from 1.20.1 in certain circumstances 

### ISSUE THREAD

**Issue by dalandis** [WiIIiam278/HuskSync#371]
We updated the plugin, transitioning from version 2.2.5 to 3.6.8, all done on version 1.20.1, carefully studying all the comments on Spigot. Then we updated the server to version 1.21.1, but encountered an unexpected problem: items in shulkers (whether in the inventory or ender chest) lost their properties. Potions lost their effects, tools and armor lost their enchantments, and item stacks reduced to a single unit (64 -> 1). We don't understand what to do.

**Comment by WiIIiam278** [comment]
This issue has been resolved through the addition of a special legacy upgrade path command
https://github.com/WiIIiam278/HuskSync/commit/50eb9a7543a7f2cfc78696783d1d20a1e3405641
