### ISSUE TITLE
Plugin wont sync attribute if stored data matches with default attribute value

### ISSUE THREAD

**Issue by thehaffk** [WiIIiam278/HuskSync#386]
https://imgur.com/bvUJSO6

> after some testing(only with generic.scale) i found out that it doesnt sync your attributes if they are "default", if scale stored in husksync is 1 it wont sync it and leave  destination server data

paper, latest alpha release

**Comment by WiIIiam278** [comment]
Closed in https://github.com/WiIIiam278/HuskSync/commit/29b3a60c64134cdab3a4a5598e1a718eca0bf6a2
