### ISSUE TITLE
After Server change - items not identified

### ISSUE THREAD

**Issue by M1904** [WiIIiam278/HuskSync#392]
Hi,

after switching the server, the player has the armor on and the entire inventory, but the armor pieces and their enchantments are not recognized. You have to take them out of the slot and insert them again so that they can be identified.

Server is Purpur 1.21.1
HuscSync 3.6.8

Best regards
Chris

**Comment by WiIIiam278** [comment]
Hey there, it sounds like you need support advice. Please join our Discord server, verify your purchase, and open a ticket for support. Thanks!
