### ISSUE TITLE
You say version 3.7.1 can also use 1.21.1. However, the latest version of PurPur 1.21.1 has an error and cannot be used.

### ISSUE THREAD

**Issue by mifjpn** [WiIIiam278/HuskSync#419]
You say version 3.7.1 can also use 1.21.1. However, the latest version of PurPur 1.21.1 has an error and cannot be used.
log out error lines

Caused by: Incompatible Minecraft version. This version of HuskSync is designed for Minecraft 1.21.3.
Please download the correct version of HuskSync for your server's Minecraft version (1.21.1).

But Will said:
"HuskSync supports Minecraft 1.20.1, 1.21.1, and 1.21.3. You must download the correct JAR file for your server version from https://william278.net/project/husksync#download"

Supports 1.21.1?

Why my latest PurPur 1.21.1 can't move version 3.7.1 ?
Pleease thanks in advance.

**Comment by WiIIiam278** [comment]
Multiple jars are published for each release. Please get in touch on discord for support related matters.
