### ISSUE TITLE
Syncing may cause item NBT order to be scrambled

### ISSUE THREAD

**Issue by Null-K** [WiIIiam278/HuskSync#425]
When syncing items with NBT data (such as custom items from ItemsAdder), there is a chance that the NBT order may get scrambled. This causes items to fail to stack properly, and some plugins that require precise item matching may not recognize the items correctly.

**Comment by Null-K** [comment]
Plugin version: 3.6.6

**Comment by Null-K** [comment]
Server: Paper 1.20.1 thx :D

**Comment by WiIIiam278** [comment]
Please attempt to reproduce with the latest plugin version
