### ISSUE TITLE
Graves support

### ISSUE THREAD

**Issue by Chiquis2005** [WiIIiam278/HuskSync#43]
does anyone know why the death chest is not created when a player goes pvp with another player? i use pvpmanager plugin, graves plugin and huskSync for inv

https://user-images.githubusercontent.com/44950448/183199956-b4529993-b539-491c-b633-a2d3b7febde7.mp4

**Comment by Chiquis2005** [comment]
if i remove the husksync plugin now it creates it without any problem

https://user-images.githubusercontent.com/44950448/183231742-e4f833ee-00cc-4026-88b7-c72f348c827e.mp4

**Comment by Chiquis2005** [comment]
any way to solve it?

**Comment by WiIIiam278** [comment]
HuskSync doesn't do any inventory clearing or anything on death; no HS code should be executed on disconnect.

I'm closing this as we don't track specific plugin incompatibilities on here

If you'd like support, please join the Discord and provide proof of purchase :-)

**Comment by WiIIiam278** [comment]
You may get some mileage out of the changes in #61 for this, if anyone's wondering (more info: https://william278.net/docs/husksync/Event-Priorities)
