### ISSUE TITLE
Not possible to take items out from the history inventory

### ISSUE THREAD

**Issue by PeterMa9621** [WiIIiam278/HuskSync#44]
Sometimes my players lost their items due to bugs or other reasons, when I review the history inventory (snapshot) of my players and try to restore only some specific items, I can only see the items but can't move any item from the history inventory to my inventory, the InventoryClick event is canceled all the time.

**Comment by WiIIiam278** [comment]
Yeah, so this is on purpose as if I let you do that people would complain "why is the inventory history not updating when I take the item out?" and it'd be confusing.

Workaround for now: Enter creative mode and use the Pick Item hotkey (middle click by default)

I might improve these menus in the future.

**Comment by PeterMa9621** [comment]
Thanks for your quick response. I don't think the Pick Item hotkey works. I tried and I am sure I am in creative mode, but no matter how I try to click the item, the event is always canceled.

**Comment by WiIIiam278** [comment]
> Thanks for your quick response. I don't think the Pick Item hotkey works. I tried and I am sure I am in creative mode, but no matter how I try to click the item, the event is always canceled.

Hm, right, looks like that's also getting cancelled -- thanks.
