### ISSUE TITLE
Visual warning for administrators

### ISSUE THREAD

**Issue by JuraRusan** [WiIIiam278/HuskSync#47]
Hello WiIIIiam278, can you make some kind of huge notification in the game, in the console, or spam that the plugin did not conditionally connect to the radis? Or let the plugin block the server from turning on. Because one line in the .log is not enough to notice the error.
<img width="1145" alt="2022-08-19_23 05 16" src="https://user-images.githubusercontent.com/76946109/185743903-a73f85ba-e599-49eb-b4a0-ec11e55dec1c.png">

Thanks in advance

**Comment by WiIIiam278** [comment]
It's against various code of conducts to have a plugin deliberately crash a server, but I do get what you're saying. I can look into doing something a bit more obvious

**Comment by JuraRusan** [comment]
Thanks, that would be great.
