### ISSUE TITLE
Player death data snapshot

### ISSUE THREAD

**Issue by ElTodoFull** [WiIIiam278/HuskSync#48]
Sometimes, dying in a server can cause issues with inventories if the player has bad connection, or the server is not running well.
Saving a snapshot when the player dies would offer a great tool to manage deaths due to bugs, bad connection or server errors/crashes (or plugin errors.)
It'd aditionally would allow me to delete a redundant, heavy plugin, that also saves data.

**Comment by WiIIiam278** [comment]
I'm kinda incredibly meh on doing this because I think it dilutes HuskSync's purpose as a synchronisation plugin primarily. It is a common request, though, so sure.

**Comment by WiIIiam278** [comment]
Done via #51
