### ISSUE TITLE
redis add so_keepalive or automatic reconnection function

### ISSUE THREAD

**Issue by Illusionika** [WiIIiam278/HuskSync#49]
My VPS hosting company has a policy on their firewall. When a TCP connection is inactive for 2 minutes, it is killed.

Just like MySQL HikariCP keepalive_time (tcp_keepalive_time) can solve this problem

But I didn't find a similar setting on redis in the configuration file, he won't even reconnect.

**Comment by WiIIiam278** [comment]
It sounds like you might need to get a new VPS hosting company to be honest -- a stable Redis connection is required here. The plugin does pool multiple Redis connections, but I'm not certain if Redis supports a parameter like that.
