### ISSUE TITLE
V2.1 database access issue

### ISSUE THREAD

**Issue by tumolomb** [WiIIiam278/HuskSync#55]
After I updated to new version and restarted, husksync fails to access the database. As soon as I roll back to prev version config and connections work just fine. 

`16.10 13:47:02 [Server] INFO [HuskSync] Loading plugin configuration settings & locales...
16.10 13:47:02 [Server] INFO [HuskSync] Successfully loaded plugin configuration settings & locales
16.10 13:47:02 [Server] INFO [HuskSync] Attempting to establish connection to the database...
16.10 13:47:02 [Server] INFO [net.william278.husksync.libraries.hikari.HikariDataSource] HuskSyncHikariPool - Starting...
16.10 13:47:07 [Server] ERROR [net.william278.husksync.libraries.hikari.pool.HikariPool] HuskSyncHikariPool - Exception during pool initialization.
16.10 13:47:07 [Server] INFO java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.libraries.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.database.MySqlDatabase.initialize(MySqlDatabase.java:104) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at net.william278.husksync.BukkitHuskSync.onEnable(BukkitHuskSync.java:126) ~[HuskSync-2.1.jar:?]
16.10 13:47:07 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
16.10 13:47:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
16.10 13:47:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
16.10 13:47:07 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-141]
16.10 13:47:07 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
16.10 13:47:07 [Server] INFO Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'15.204.145.99' (using password: YES)
16.10 13:47:07 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
16.10 13:47:07 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
16.10 13:47:07 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
16.10 13:47:07 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
16.10 13:47:07 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
16.10 13:47:07 [Server] INFO at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:848) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:770) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:738) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:155) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:472) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:212) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1433) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.NativeSession.connect(NativeSession.java:133) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842) ~[mysql-connector-java-8.0.29.jar:8.0.29]
16.10 13:47:07 [Server] INFO ... 24 more
16.10 13:47:07 [Server] ERROR [HuskSync] Failed to perform database setup: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
16.10 13:47:07 [Server] ERROR [HuskSync] ***************************************************
16.10 13:47:07 [Server] INFO Failed to initialize HuskSync!
16.10 13:47:07 [Server] INFO ***************************************************
16.10 13:47:07 [Server] INFO The plugin was disabled due to an error. Please check
16.10 13:47:07 [Server] INFO the logs below for details.
16.10 13:47:07 [Server] INFO No user data will be synchronised.
16.10 13:47:07 [Server] INFO ***************************************************
16.10 13:47:07 [Server] INFO Caused by: Failed to establish a connection to the database. Please check the supplied database credentials in the config file
16.10 13:47:07 [Server] ERROR [HuskSync] Failed to initialize HuskSync. The plugin will now be disabled
16.10 13:47:07 [Server] INFO [HuskSync] Disabling HuskSync v2.1
16.10 13:47:07 [Server] INFO [HuskSync] Successfully disabled HuskSync v2.1`

**Comment by WiIIiam278** [comment]
You didn't follow the instructions to regenerate your config file when upgrading between 2.0.2 and 2.1. Regenerate your config and messages as per instructions. Please read the changelogs.

**Comment by tumolomb** [comment]
Oops sorry about that thank u
