### ISSUE TITLE
Players Inventory Item NBT datas are lost.

### ISSUE THREAD

**Issue by g2213swo** [WiIIiam278/HuskSync#64]
When shutting down a Paper server normally, HuskSync will lose some data like custom enchantments when storing items NBT in the players' inventory but vanilla enchantments are not lost. Sometimes all the  items in inventory of the players will be lost! (I am not good at English, so I used Google Translator)

**Comment by WiIIiam278** [comment]
HuskSync only supports serialising item data saved in the persistent data container; plugins that do proprietary stuff with the raw item NBT won't work. Most modern plugins however should support setting values through the PDC.
