### ISSUE TITLE
Improve synchronization system stability on environments with fluctuating tick rates

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#69]
Currently, the `network_latency_milliseconds` is used to account for the expected lag in handling player disconnects to allow the plugin to serialize and save UserData to Redis. However, on environments where the tick rate fluctuates significantly or those that are prone to sharp lag spikes the predetermined wait can not be enough to account for how much the `PlayerQuitEvent` is getting delayed from the source server.

Reworking parts of how the synchronization system works to accommodate such environments and prevent user data versions from going out of sync is needed here, which requires a fairly significant adjustment to the approach to track when players join and leave the network versus changing servers, using Redis PubSub messages to query the current set of connected players and "locking" players when changing server.

This issue is a follow-up to a discussion on the Discord, cc. noahiversen et al. (who provided the below diagrams to illustrate how an updated approach may be formed.)
<details>
<summary>Updated implementation diagram</summary>

![image](https://user-images.githubusercontent.com/31187453/202871046-ad7db569-4681-462d-9963-e979b6647da0.png)
![image](https://user-images.githubusercontent.com/31187453/202871050-20248821-eb99-47d8-8984-1bf4f5774e7b.png)
</details>

**Comment by liaojinmin** [comment]
Set a master server, simulate the registration center, and track the status of all sub-server players on a regular basis. During the cross-server period, only after the sub-server publishing data is set, can the data be actively queried

**Comment by WiIIiam278** [comment]
> Set a master server, simulate the registration center, and track the status of all sub-server players on a regular basis. During the cross-server period, only after the sub-server publishing data is set, can the data be actively queried

Sorry, could you clarify what you mean by this? :) A master server? A registration center? I'm not totally sure what you mean

**Comment by liaojinmin** [comment]
For data stability, it may be necessary to sacrifice the game experience...........

**Comment by WiIIiam278** [comment]
I sort of see what you're saying, but it's not the approach I'm looking into at this time. HuskSync version 1 operated under a single proxy approach and was flawed for various reasons. 

The approach described in the original post is something I'd like to work on in the future to alleviate issues with fluctuating delay, but in the case of the vast majority of servers where that's not a concern, the current approach is sufficient.

**Comment by liaojinmin** [comment]
He will suspend players who are crossing servers and wait for data
https://github.com/liaojinmin/GeekScheduler/blob/master/src/main/kotlin/me/geek/scheduler/service/RegistrationCenter.kt

**Comment by WiIIiam278** [comment]
The [lockstep-syncing](https://github.com/WiIIiam278/HuskSync/tree/lockstep-syncing) branch refactors the syncing process into a modular system, and introduces a lockstep syncing approach inspired by the specification originally proposed in the OP :)

This also introduces a mandate for implementing a server config per-server; which also paves the way for probably saving the server where data was saved into the snapshot in the future (very handy for admins, of course!).

I'd also like to probably introduce API in this branch to let devs implement their own syncing method if they so wish.

Comments welcome in `#husksync-dev` on Discord.
