### ISSUE TITLE
HuskSync and EcoEnchants in will result in the loss of NBT

### ISSUE THREAD

**Issue by MrLaoGe** [WiIIiam278/HuskSync#70]
My English is poor, please forgive my machine translation
HuskSync 2.1.2 
EcoEnchants 8.111.0
Server purpur 1.19.2
MySQL： 8.0.0
Redis：5.0.10

When the player jumps to the server, HuskSync will cause EcoEnchants to lose EnchantsNBT
For example, NBT：
Enchantments(List){"Stat":"ENCHANTS","OGStory":[{"MMOITEMS_ENCHANTS_ñstr":"[\"bolt 9\",\"plasmic 10\",\"razor 10\",\"criticals 10\",\"thor 10\",\"parry 6\",\"zap_artifact 1\"]"}]}

My friend he is HuskSync 2.1 EcoEnchants 8.111.0 and did not have this problem

Hope the author can fix this BUG

**Comment by WiIIiam278** [comment]
HuskSync will sync the persistent data container tags and doesn't sync custom NBT; more likely then not EcoEnchants is using the PDC, however it's possible something broke or the format changed in an update? We don't provide tracking for individual plugin issues or compatibility, so I'm closing this.

**Comment by MrLaoGe** [comment]
> HuskSync will sync the persistent data container tags and doesn't sync custom NBT; more likely then not EcoEnchants is using the PDC, however it's possible something broke or the format changed in an update? We don't provide tracking for individual plugin issues or compatibility, so I'm closing this.

Yes, items in Shulker Box will not be a problem, items in the backpack will be lost NBT

**Comment by WiIIiam278** [comment]
> > HuskSync will sync the persistent data container tags and doesn't sync custom NBT; more likely then not EcoEnchants is using the PDC, however it's possible something broke or the format changed in an update? We don't provide tracking for individual plugin issues or compatibility, so I'm closing this.
> 
> 
> 
> Yes, items in Shulker Box will not be a problem, items in the backpack will be lost NBT

Modded items that utilise proprietary item formats aren't currently supported in general in favour of supporting the PDC API
