### ISSUE TITLE
Issues about sync

### ISSUE THREAD

**Issue by ShiFtXe** [WiIIiam278/HuskSync#71]
Plugin-Version: 2.1.2
Server: Purpur-1.19.2-build1794
Mysql: 8.0
Redis: 5.0.10
Sorry for my poor english,this is my issue about Husksync.
I made an Afk server for players, so that my survival server would have more space for other players, and i set all the settings to false except experience sync on the Afk server, so that my players can gain experience while they are afk .
But in this situation, i found that some items in inventory would be lost .
For example  I teleport to Afk server on ResourceWorld server , some of my items would be gone except experience ,
                     cause i made  that.
                     Then I teleport back to Hub server ,i found that some items that i gain in ResourceWorld is gone!
                     It's like the data return back to the old version when i leave the Hub server.
                     I think  the reason is that i teleport back to the server , the Hub server, that is not the last server i leave ,and 
                     Husksync on this server , the Hub server ,  didn't get the Afk server's inventory cause inventory sync has been 
                     set to false on the Afk server, 
                     so the server(the hub server)chose to get the old version of the inventory when the player i leave the hub server.
                     (The reason that i teleport back to Hub server is that i can't appoint the last server to teleport , cause the plugin 
                     DeluxeHub can only appoint one server .)
I have some solutions
①Add a new command /husksync lastserver ,so that players can be teleported to the last server they leave.
②Change the logic of preserving data,so that there would be no problems.
Sorry for bothering you,Hope you can fix this.Have a nice day!
Thank you !

**Comment by WiIIiam278** [comment]
Hi, I'm not able to reproduce this issue. This seems more in the line of a support issue, and I suggest joining the discord and getting support through a ticket after completing purchase verification.
