### ISSUE TITLE
inventory lose !!

### ISSUE THREAD

**Issue by xbaimiao** [WiIIiam278/HuskSync#72]
Players have a chance to lose their inventory!!

Players who exit the server have a chance to lose their inventory when entering

**Comment by xF3d33** [comment]
no one can help you if you don't tell us what's the issue and how to reproduce it.

**Comment by xbaimiao** [comment]
> no one can help you if you don't tell us what's the issue and how to reproduce it.

Players who exit the server have a chance to lose their inventory when entering

**Comment by WiIIiam278** [comment]
I cannot reproduce this -- please open a support ticket, providing proof of purchase for further assistance.
