### ISSUE TITLE
Player lock state prevents an item on inventory cursor from being automatically dropped on disconnect

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#74]
The item on the player's inventory cursor should be dropped when the player closes an open inventory or disconnects. However, HuskSync prevents this behavior on disconnect as the DropItem event is cancelled when the player is locked for data saving. A special case ought to be added here to ensure the cursor item is properly dropped when the user disconnects/changes server.

**Comment by alexdev03** [comment]
When a user leaves, check if [HumanEntity#getItemOnCursor](https://helpch.at/docs/1.16.5/org/bukkit/entity/HumanEntity.html#getItemOnCursor()) is not empty, then drop it with [World#dropItem ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#dropItem(org.bukkit.Location,org.bukkit.inventory.ItemStack))

**Comment by WiIIiam278** [comment]
> When a user leaves, check if [HumanEntity#getItemOnCursor](https://helpch.at/docs/1.16.5/org/bukkit/entity/HumanEntity.html#getItemOnCursor()) is not empty, then drop it with [World#dropItem ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#dropItem(org.bukkit.Location,org.bukkit.inventory.ItemStack))

Yeah, pretty much. Just have to be careful to not accidentally introduce duplication issues with this. PR's welcome!

**Comment by iVillager** [comment]
The code from @ItsWagPvP works. You can close the issue
