### ISSUE TITLE
Wiki Section on this Repo

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskSync#8]
Due to abundant questions on setup and how features of HuskSync works it'd seem only fair to allow for a Wiki section of this Repo to be added including such areas as:

- Basic Guide to installing and setting up Redis
- A FAQ section 
- A Roadmap 
- Details on the Events API
and more...

**Comment by WiIIiam278** [comment]
Agreed

**Comment by Iotados** [comment]
Notably of course, maybe instead of a Basic Guide having a more "Set-up" and then "Maintaining" section would be great along side a short FAQ at the end for Redis. As it seems to be the bulk of our HuskSync Queries

**Comment by mfnalex** [comment]
To be fair, installing Redis is as simple as `apt install redis-server` in most distros.

**Comment by WiIIiam278** [comment]
Still a WIP but closing this for now as it can be worked on by staff as needed. If anyone wants to contribute to docs, email or discord me.
