### ISSUE TITLE
Add an empty line between inventory view and deletion

### ISSUE THREAD

**Issue by JuraRusan** [WiIIiam278/HuskSync#80]
Hello, could you add an empty line between inventory view and deletion, you are always afraid to click and delete with an awkward movement.

![image](https://user-images.githubusercontent.com/76946109/211658885-f9da5257-34f4-432e-acf1-2d9a60aa39e0.png)

Thanks in advance!

**Comment by WiIIiam278** [comment]
I'll look into moving delete and restore to the right end of that line.

**Comment by WiIIiam278** [comment]
Closing this for now as awhile back this was changed so the delete button only suggests the command
